# Site settings
title: Portfolio
subtitle: by Andrés Zúñiga González
email: ancazugo@hotmail.com
description: A portfolio by Andrés Zúñiga González
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Bogotá
# city: Nashville
# state: TN
# zip_code: 55555
country: Colombia
phone: (+57) 318 869 26 15

# Social settings
facebook_url: https://facebook.com/ancazugo
github_url: https://github.com/ancazugo
# gitlab_url: https://gitlab.com/u/andrewbanchich
researchgate_url: https://www.researchgate.net/profile/Andres-Zuniga-Gonzalez
instagram_url: https://instagram.com/ancazugo
linkedin_url: https://www.linkedin.com/in/ancazugo
# pinterest_url:
# slack_url:
twitter_url: https://twitter.com/ancazugo
google_scholar: https://scholar.google.com/citations?user=9guCE0wAAAAJ&hl=es&oi=ao
researchgate: https://www.researchgate.net/profile/Andres-Zuniga-Gonzalez
google_analytics: G-0WBJKLJYX9
updated: March 2022
# Build settings
markdown: kramdown
