# Site settings
title: Portfolio
subtitle: by Andrés Zúñiga González
email: ancazugo@hotmail.com; acz25@cam.ac.uk
description: A portfolio by Andrés Zúñiga González
url: "https://ancazugo.github.io"  # Your website's full URL
baseurl: ""  # Leave empty if your site is at the root
author:
street_address: Cambridge
country: United Kingdom
phone: (+44) 07858 600851

# Social settings
facebook_url: https://facebook.com/ancazugo
github_url: https://github.com/ancazugo
# gitlab_url: https://gitlab.com/u/andrewbanchich
researchgate_url: https://www.researchgate.net/profile/Andres-Zuniga-Gonzalez
instagram_url: https://instagram.com/ancazugo
linkedin_url: https://www.linkedin.com/in/ancazugo
twitter_url: https://twitter.com/ancazugo
google_scholar: https://scholar.google.com/citations?user=9guCE0wAAAAJ&hl=es&oi=ao
researchgate: https://www.researchgate.net/profile/Andres-Zuniga-Gonzalez
google_analytics: G-0WBJKLJYX9
updated: February 2025
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
feed:
  url: ancazugo.github.io/feed.xml

